### ISSUE TITLE
Complex Assemblies Crashing Browsers

### ISSUE THREAD

**Issue by skalnik** [iliterobotics/3D#1]
Hiya! Your README mentions there are some complex files that are crashing browsers. I started looking through the files to find said files, but there is not a small amount in this repository. Could you point me to what files are causing issues?

/cc @sshirokov

**Comment by pixelyunicorn** [comment]
This appears to be the problem file:

https://github.com/iliterobotics/3D/blob/master/Robot2013/RobotAssembly.stl

It is supposed to look like this when properly rendered:

https://github.com/iliterobotics/3D/blob/master/Robot2013/Pics/Render_29Jan2013.png

It crashes Chrome on the low-end school computers running Windows XP, freezes before it renders halfway on many other browsers. It's a pretty large file, but there should be some notice that it either rendered halfway or that a browser is not capable of rendering the whole assembly.

The last thing I was told from support was that they were working on a fix.

**Comment by pixelyunicorn** [comment]
It turns out that the few problem files were not exported properly and had lots of misplaced parts when I tried to opened them in Inventor.

I have fixed that for now, and I'm closing this issue.
